import '../models/product.dart';

class FakeData {
  static List<Product> get sampleProducts => [
    Product(
      id: 'product_001',
      name: 'Nike Sports Shoes',
      description:
          'Premium Nike sports shoes designed for comfort and performance. Perfect for running, training, and everyday wear.',
      originalPrice: 299,
      discountedPrice: 199,
      discountPercentage: 33,
      images: ['assets/products/adidas2.jpg'],
      rating: 4.5,
      reviews: 1250,
      brand: 'Nike',
      category: 'Sports',
      sellerName: 'SportZone',
      sellerLocation: 'Tunis, Tunisia',
      inStock: true,
      freeShipping: true,
      specifications: [
        'Lightweight mesh upper',
        'Air cushioning technology',
        'Durable rubber outsole',
        'Breathable interior lining',
        'Available in multiple sizes',
      ],
      tags: ['nike', 'shoes', 'sports', 'running', 'comfortable'],
      isFavorite: false,
    ),
    Product(
      id: 'product_002',
      name: 'Smart Fitness Watch',
      description:
          'Advanced fitness tracker with heart rate monitoring, GPS tracking, and water resistance. Track your health 24/7.',
      originalPrice: 450,
      discountedPrice: 299,
      discountPercentage: 34,
      images: ['assets/products/smartwatch.jpg'],
      rating: 4.3,
      reviews: 890,
      brand: 'FitTrack',
      category: 'Electronics',
      sellerName: 'Fitness Gear Store',
      sellerLocation: 'Sfax, Tunisia',
      inStock: true,
      freeShipping: true,
      specifications: [
        '1.4-inch AMOLED display',
        'GPS + GLONASS tracking',
        'Heart rate & sleep monitoring',
        '50m water resistance',
        '7-day battery life',
        'Multiple sport modes',
      ],
      tags: ['smartwatch', 'fitness', 'health', 'gps', 'waterproof'],
      isFavorite: true,
    ),
    Product(
      id: 'product_003',
      name: 'Gaming Chair',
      description:
          'Ergonomic gaming chair with lumbar support and adjustable height. Perfect for long gaming sessions and office work.',
      originalPrice: 189,
      discountedPrice: 129,
      discountPercentage: 32,
      images: ['assets/products/chair.jpg'],
      rating: 4.2,
      reviews: 756,
      brand: 'GameComfort',
      category: 'Furniture',
      sellerName: 'Office Solutions',
      sellerLocation: 'Sousse, Tunisia',
      inStock: true,
      freeShipping: true,
      specifications: [
        'Ergonomic lumbar support',
        'Adjustable height mechanism',
        'High-quality leather upholstery',
        '360-degree swivel base',
        'Weight capacity: 150kg',
      ],
      tags: ['gaming', 'chair', 'ergonomic', 'office', 'furniture'],
      isFavorite: false,
    ),
  ];
}
